package com.bdlepla.android.mymusicplayer.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF00687b)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFa7edff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f26)
val md_theme_light_secondary = Color(0xFF7d5800)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdea2)
val md_theme_light_onSecondaryContainer = Color(0xFF271900)
val md_theme_light_tertiary = Color(0xFF006d3b)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF88f9b1)
val md_theme_light_onTertiaryContainer = Color(0xFF00210e)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1d1b1e)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1d1b1e)
val md_theme_light_surfaceVariant = Color(0xFFdbe4e7)
val md_theme_light_onSurfaceVariant = Color(0xFF3f484b)
val md_theme_light_outline = Color(0xFF70797c)
val md_theme_light_inverseOnSurface = Color(0xFFf6eff3)
val md_theme_light_inverseSurface = Color(0xFF322f33)
val md_theme_light_inversePrimary = Color(0xFF55d6f4)
//val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF55d6f4)
val md_theme_dark_onPrimary = Color(0xFF003641)
val md_theme_dark_primaryContainer = Color(0xFF004e5d)
val md_theme_dark_onPrimaryContainer = Color(0xFFa7edff)
val md_theme_dark_secondary = Color(0xFFf7bd48)
val md_theme_dark_onSecondary = Color(0xFF422d00)
val md_theme_dark_secondaryContainer = Color(0xFF5e4100)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdea2)
val md_theme_dark_tertiary = Color(0xFF6cdc97)
val md_theme_dark_onTertiary = Color(0xFF00391c)
val md_theme_dark_tertiaryContainer = Color(0xFF00522b)
val md_theme_dark_onTertiaryContainer = Color(0xFF88f9b1)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1d1b1e)
val md_theme_dark_onBackground = Color(0xFFe7e0e5)
val md_theme_dark_surface = Color(0xFF1d1b1e)
val md_theme_dark_onSurface = Color(0xFFe7e0e5)
val md_theme_dark_surfaceVariant = Color(0xFF3f484b)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc8cb)
val md_theme_dark_outline = Color(0xFF899295)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe7e0e5)
val md_theme_dark_inversePrimary = Color(0xFF00687b)
//val md_theme_dark_shadow = Color(0xFF000000)

//val seed = Color(0xFF6750A4)
//val error = Color(0xFFba1b1b)